### ISSUE TITLE
[FEATURE]: Simple installation 

### ISSUE THREAD

**Issue by ilkerhk** [gikari/bismuth#66]
### Summary

Hi,
Thank you for forking and maintaining krohnkite. 
I think it would be nice if you can provide a simpler installation procedure (similar to other kwin scripts). 
Usually installing a kwin script is done with few files. I couldn't do that with bismuth. 

### A clear and concise description of what you want to happen

I had to install npm and run two scripts using npm (which I don't know what it is doing) and it took much longer compared to builtin kpackagetool5 .
 Usual kwin installation using kpackagetool5 is much simpler and familiar to KDE users.

**Comment by gikari** [comment]
Yeah, that's is planned. This is what I try to achieve in #56. You see, if I just release the .kwinscript file - it will work, but the user will have to do some manual tweaks - such as enabling user configuration. I want to fix that by packing everything in archive and put an installation script in it, so that the script will do all these tricks automatically. 

I do not yet if it will work with Scripts KCM. If not I will settle with just the .kwinscript, but provide the installation instructions in the description.

**Comment by gikari** [comment]
Hm, my testing showed, that the simple installation method is not possible via KCM, if we are trying to execute the installation script. Given that the installation script it pretty important, as it works around some issues, such as icon installation and the configuration button fix, I think the most viable solution is to publish the archive to Pling and state in the description to install the script via some simple curl-like command (like you can see [here](https://www.rust-lang.org/learn/get-started) for example).
