### ISSUE TITLE
[FEATURE]: Bismuth crash in / Support for KwinFT 

### ISSUE THREAD

**Issue by v3ss0n** [gikari/bismuth#73]
### Summary

Bismuth won't work in KWinFT

### A clear and concise description of what you want to happen

KWinFT makes KWin a lot smmother : https://gitlab.com/kwinft/kwinft  works much better on Wayland.
Currently It is stable and working  alot better when multiple windows are opened at the same time . Much smoother experience overall.
KWinFT have a few breaking api changes so most scripts won't work.

For Bismuth , the error is :
```
qml: Registering bismuth_rotate with the description Bismuth: Rotate
qml: Registering bismuth_rotate_part with the description Bismuth: Rotate Part
file:///home/nozander/.local/share/kwin/scripts/bismuth/contents/code/index.mjs:1940: TypeError: Cannot read property 'x' of undefined
```
Error is at

```
// src/util/kwinutil.ts
function toQRect(rect) {
  return Qt.rect(rect.x, rect.y, rect.width, rect.height);
}
function toRect(qrect) {
  return new Rect(qrect.x, qrect.y, qrect.width, qrect.height);
}

```

### A clear and concise description of any alternative solutions or features you've considered.

Since major (Arch/Manjaro) distros are started supporting  it would be nice if BIsmuth works on KwinFT

### Additional info

https://gitlab.com/kwinft/kwinft

**Comment by gikari** [comment]
Thank you for reporting the issue. :bow: 

Unfortunately support of two separate APIs is not viable. It requires too much work and complicates the code base, which is rather complicated already due to the fact, that Bismuth is de facto a window manager inside a window manager. 

From what I understand (I could be wrong), KWinft is not a KDE project, and it is maintained by only one person (not the team), therefore making the project rather risky and vulnerable to abandonment. It also breaks a lot of stuff in the Plasma stack, and therefore it is expected that all KWin scripts won't work. If you want KWin scripts (including Bismuth) to work with the new implementation, you should encourage the author to provide full backwards compatibility with the scripting engine, and/or upstream their patches to the original KWin if it is possible, which in some cases could be a plus, since KWin API is not ideal.

I apologize, but I think you would understand the perspective.
